name: install-rubygems

on:
  pull_request:

  push:
    branches:
      - master
      - 3.2
      - propagate_env_shebang

jobs:
  install_rubygems_ubuntu:
    name: Install Rubygems on ${{ matrix.os.name }} (${{ matrix.ruby.name }}, ${{ matrix.openssl.name }})
    runs-on: ${{ matrix.os.value }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - { name: MacOS, value: macos-10.15 }
        ruby:
          - { name: jruby-9.2, value: jruby-9.2.14.0 }
        openssl:
          - { name: "openssl", value: true }
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Uninstall jruby-launcher
        run: gem uninstall jruby-launcher
        if: matrix.ruby.name == 'jruby-9.2'
      - name: Install rubygems (Ubuntu)
        run: ruby -Ilib -S rake install 2> errors.txt || (cat errors.txt && exit 1)
        if: matrix.os.name == 'Ubuntu'
      - name: Install rubygems (MacOS)
        run: ruby setup.rb 2> errors.txt || (cat errors.txt && exit 1)
        if: matrix.os.name == 'MacOS'
      - name: Check rubygems install produced no warnings
        run: test ! -s errors.txt || (cat errors.txt && exit 1)
      - name: Run a local rubygems command
        run: gem list bundler
        env:
          RUBYOPT: -Itest/rubygems/fake_certlib
        if: matrix.openssl.value == false
      - name: Run a local rubygems command
        run: gem list
        if: matrix.openssl.value == true
      - name: Run a remote rubygems command
        run: gem outdated
        if: matrix.openssl.value == true
      - name: Run bundler installed as a default gem
        run: bundle --version
      - name: Check bundler man pages were installed and are properly picked up
        run: bundle install --help | grep -q BUNDLE-INSTALL
        if: matrix.ruby.name != 'truffleruby-20.3'
      - name: Check bundler fallback man pages are properly picked up
        run: sudo rm $(which man) && bundle install --help
        if: matrix.ruby.name != 'truffleruby-20.3'
      - name: Build bundler
        run: gem build bundler.gemspec
        working-directory: ./bundler
      - name: Install built bundler
        run: gem install bundler-*.gem --verbose --backtrace > output.txt
        working-directory: ./bundler
      - name: Check bundler install didn't hit the network
        run: if grep -q 'GET http' output.txt; then false; else true; fi
        working-directory: ./bundler
      - name: Check rails can be installed
        run: gem install rails --verbose --backtrace
        if: matrix.ruby.name != 'truffleruby-20.3'
    timeout-minutes: 10

  install_rubygems_windows:
    name: Install Rubygems on Windows (${{ matrix.ruby.name }})
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - { name: "3.0", value: 3.0.0 }
          - { name: jruby-9.2, value: jruby-9.2.14.0 }
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install rubygems
        run: ruby setup.rb
        shell: bash
      - name: Check installation didn't modify any source controlled files
        run: git diff --exit-code
        shell: bash
      - name: Check we can install a Gemfile with git sources
        run: bundle init && bundle add fileutils --git https://github.com/ruby/fileutils
        shell: bash

    timeout-minutes: 10
