name: system-rubygems-bundler

on:
  pull_request:
    paths:
      - bundler/**
      - .github/workflows/system-rubygems-bundler.yml

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

defaults:
  run:
    shell: bash

jobs:
  system_rubygems_bundler:
    name: Bundler ${{ matrix.bundler }} against system Rubygems (${{ matrix.ruby.name }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { bundler: 2, ruby: { name: ruby-3.2, value: 3.2.0 } }
          - { bundler: 2, ruby: { name: ruby-3.3, value: 3.3.0 } }
          - { bundler: 2, ruby: { name: ruby-3.4, value: 3.4.1 } }
          - { bundler: 3, ruby: { name: ruby-3.2, value: 3.2.0 } }
          - { bundler: 3, ruby: { name: ruby-3.3, value: 3.3.0 } }
          - { bundler: 3, ruby: { name: ruby-3.4, value: 3.4.1 } }
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Setup ruby
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1.244.0
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler: none
      - name: Install graphviz
        run: sudo apt-get install graphviz -y
        if: matrix.bundler == 2
      - name: Set version
        run: echo "BUNDLER_3_MODE=true" >> $GITHUB_ENV
        if: matrix.bundler == 3
      - name: Prepare dependencies
        run: |
          bin/rake dev:deps
      - name: Run Test
        run: |
          bin/parallel_rspec
        working-directory: ./bundler
      - name: Save system RubyGems version to ENV
        run: |
          RGV=$(ruby -e 'puts Gem::VERSION.split(".")[0..2].join(".")')
          echo "RGV=v$RGV" >> $GITHUB_ENV
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: bundler/tmp/rubygems
          ref: ${{ env.RGV }}
          persist-credentials: false
      - name: Run Rubygems Requirement tests against local bundler, to make sure bundler monkeypatches preserve the behaviour
        run: |
          ruby -I../../lib:lib:test test/rubygems/test_gem_requirement.rb
        working-directory: ./bundler/tmp/rubygems
    timeout-minutes: 60
